#pragma once

#define SECTOR_SIZE_BYTES 0x10000
#define SECTOR_ADDR_MASK (~(SECTOR_SIZE_BYTES - 1))

#define SUBSECTOR_SIZE_BYTES 0x1000
#define SUBSECTOR_ADDR_MASK (~(SUBSECTOR_SIZE_BYTES - 1))
#define FLASH_FILESYSTEM_BLOCK_SIZE SUBSECTOR_SIZE_BYTES

// Filesystem layout
///////////////////////////////////////
#define FIRMWARE_SCRATCH_SIZE (0x200000) /* 2048k */
#define SYSTEM_RESOURCES_BANK_0_SIZE (0x100000) /* 1024k */
#define SYSTEM_RESOURCES_BANK_1_SIZE (0x100000) /* 1024k */
#define SAFE_FIRMWARE_SIZE (0x080000) /* 512k */
#define DEBUG_DB_SIZE (0x020000) /* 128k */
#define MFG_INFO_SIZE (0x020000) /* 128k */
#define FILESYSTEM_SIZE (0x800000) /* 8M */
#define RSVD_SIZE (0x00F000) /* 60k */
#define SHARED_PRF_STORAGE_SIZE (0x001000) /* 4k */

#define FLASH_REGION_FIRMWARE_BASE_ADDRESS (0x12300000) // 3M
#define FLASH_REGION_FIRMWARE_SCRATCH_BEGIN (FLASH_REGION_FIRMWARE_BASE_ADDRESS)
#define FLASH_REGION_FIRMWARE_SCRATCH_END (FLASH_REGION_FIRMWARE_BASE_ADDRESS + FIRMWARE_SCRATCH_SIZE)
#define FLASH_REGION_SYSTEM_RESOURCES_BANK_0_BEGIN (FLASH_REGION_FIRMWARE_SCRATCH_END)
#define FLASH_REGION_SYSTEM_RESOURCES_BANK_0_END (FLASH_REGION_SYSTEM_RESOURCES_BANK_0_BEGIN + SYSTEM_RESOURCES_BANK_0_SIZE)
#define FLASH_REGION_SYSTEM_RESOURCES_BANK_1_BEGIN (FLASH_REGION_SYSTEM_RESOURCES_BANK_0_END)
#define FLASH_REGION_SYSTEM_RESOURCES_BANK_1_END (FLASH_REGION_SYSTEM_RESOURCES_BANK_1_BEGIN + SYSTEM_RESOURCES_BANK_1_SIZE)
#define FLASH_REGION_SAFE_FIRMWARE_BEGIN (FLASH_REGION_SYSTEM_RESOURCES_BANK_1_END)
#define FLASH_REGION_SAFE_FIRMWARE_END (FLASH_REGION_SAFE_FIRMWARE_BEGIN + SAFE_FIRMWARE_SIZE)
#define FLASH_REGION_DEBUG_DB_BEGIN (FLASH_REGION_SAFE_FIRMWARE_END)
#define FLASH_REGION_DEBUG_DB_END (FLASH_REGION_DEBUG_DB_BEGIN + DEBUG_DB_SIZE)
#define FLASH_DEBUG_DB_BLOCK_SIZE SUBSECTOR_SIZE_BYTES
#define FLASH_REGION_MFG_INFO_BEGIN (FLASH_REGION_DEBUG_DB_END)
#define FLASH_REGION_MFG_INFO_END (FLASH_REGION_MFG_INFO_BEGIN + MFG_INFO_SIZE)
#define FLASH_REGION_FILESYSTEM_BEGIN (FLASH_REGION_MFG_INFO_END)
#define FLASH_REGION_FILESYSTEM_END (FLASH_REGION_FILESYSTEM_BEGIN + FILESYSTEM_SIZE)
#define FLASH_FILESYSTEM_BLOCK_SIZE SUBSECTOR_SIZE_BYTES
#define FLASH_REGION_SHARED_PRF_STORAGE_BEGIN (FLASH_REGION_FILESYSTEM_END)
#define FLASH_REGION_SHARED_PRF_STORAGE_END (FLASH_REGION_SHARED_PRF_STORAGE_BEGIN + SHARED_PRF_STORAGE_SIZE)
#define FLASH_REGION_RSVD_BEGIN (FLASH_REGION_SHARED_PRF_STORAGE_END)
#define FLASH_REGION_RSVD_END (FLASH_REGION_RSVD_BEGIN + RSVD_SIZE)
#define FLASH_REGION_SHARED_PRF_STORAGE_SIZE (FLASH_REGION_SHARED_PRF_STORAGE_END - FLASH_REGION_SHARED_PRF_STORAGE_BEGIN)
#define FLASH_REGION_RSVD_SIZE (FLASH_REGION_RSVD_END - FLASH_REGION_RSVD_BEGIN)

#define BOARD_NOR_FLASH_SIZE (3*1024*1024 + FIRMWARE_SCRATCH_SIZE + SYSTEM_RESOURCES_BANK_0_SIZE + SYSTEM_RESOURCES_BANK_1_SIZE + SAFE_FIRMWARE_SIZE + DEBUG_DB_SIZE + MFG_INFO_SIZE + FILESYSTEM_SIZE + RSVD_SIZE + SHARED_PRF_STORAGE_SIZE)